### ISSUE TITLE
Problem in running with SALSA (FATAL:   "salsa": executable file not found in $PATH)

### ISSUE THREAD

**Issue by Hai1983** [aakashsur/docker-salsa#1]
Dear authors.

I try to run SALSA with singularity.
But I faced a issue: 

daomhai@nic5-login1 /scratch/ulg/bbasv/daomhai/SALSADocker $ singularity run -B /scratch/users/d/a/daomhai/SALSADocker /scratch/users/d/a/daomhai/SALSADocker/salsa_latest.sif salsa -a Chr30.fasta -l Chr30.fasta.fai -b hai1.alignment.bed -e GATC -o scaffoldsHai1
FATAL:   "salsa": executable file not found in $PATH

Please help me to figure out what i doing wrong ?
Sincerely,
Hai

**Comment by aakashsur** [comment]
Your `-B` flag needs to have a destination path. Usually its formatted like such `-B /path/on/local/system:/path/on/container`. Try using the command on the README as that's the one I've tested the container with. Just run it in the folder you want the results and have the available files hard linked or copied into the folder. 

```
singularity run \
	--bind $PWD:/root/results \
	--home $PWD:/root/results \
	~/software/salsa/salsa_latest.sif \
	salsa \
	    -a assembly.fasta \
	    -l assembly.fasta.fai \
	    -b alignment.bed \
	    -e GATC \
	    -o scaffolds
```

**Comment by Hai1983** [comment]
Hi Aakashsur.

Thank for your reply. 
I did my job like this:
With the path to my folder (SALSADocker with all necessary file): /scratch/ulg/bbasv/daomhai/SALSADocker 

singularity run --bind $PWD:/scratch/ulg/bbasv/daomhai/SALSADocker \
--home $PWD:/scratch/ulg/bbasv/daomhai/SALSADocker \
 /scratch/users/d/a/daomhai/SALSADocker/salsa_latest.sif \
salsa\
 -a Chr30.fasta\
 -l Chr30.fasta.fai\
 -b hai1.alignment.bed\
 -e GATC\
 -o scaffoldsHai1\
FATAL:   "salsa": executable file not found in $PATH.

Please show me what I am doing wrong ?? 
Sincerely,
Hai

**Comment by aakashsur** [comment]
Use these commands

```
cd /scratch/ulg/bbasv/daomhai/SALSADocker

singularity run \
	--bind $PWD:/root/results \
	--home $PWD:/root/results \
	/scratch/users/d/a/daomhai/SALSADocker/salsa_latest.sif \
	salsa \
	    -a Chr30.fasta \
	    -l Chr30.fasta.fai \
	    -b hai1.alignment.bed \
	    -e GATC \
	    -o scaffoldsHai1
```

**Comment by Hai1983** [comment]
Thanks for your kind reply.
It is very usefull to me..
Another point, do you have some tips to improve the scaffold N50 of genome with SALSA.

Thank you in advances.

Sincerely,
Hai

**Comment by aakashsur** [comment]
Glad to hear it worked. I don't believe Salsa has much in the way of tuning parameters. If salsa didn't give good results, you might try Lachesis (docker version [here](https://github.com/aakashsur/docker-hirise)) or HiRise (docker version [here](https://github.com/aakashsur/docker-hirise)).
